name: kubbr
version: 0.1.0.0
github: "mincomk/kubbr"
license: BSD3
author: "MincoMK"
maintainer: "mail@drchi.co.kr"
extra-source-files:
  - README.md

library:
  source-dirs: src
  dependencies:
    - base
    - text
    - optparse-applicative
    - yaml
    - aeson

executables:
  kubbr:
    main: Main.hs
    source-dirs: app
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - optparse-applicative

      - kubbr

tests:
  kubbr-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base

      - text
      - aeson
      - yaml

      - kubbr

      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - QuickCheck
